-- 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE)
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
HAVING ANIMAL_TYPE = 'Cat' OR ANIMAL_TYPE = 'Dog'
ORDER BY ANIMAL_TYPE ASC;
-- 동명 동물 수 찾기
SELECT NAME, COUNT(NAME)
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME)>=2
ORDER BY NAME ASC;
-- 입양 시각 구하기(1)
SELECT HOUR(DATETIME) HOUR, COUNT(DATETIME) COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR >= 9 and HOUR <= 19
ORDER BY HOUR;
-- 입양 시각 구하기(2)
SET @hour := -1;

SELECT (@hour := @hour + 1) as HOUR,
(SELECT COUNT(*) 
 FROM ANIMAL_OUTS 
 WHERE HOUR(DATETIME) = @hour) as COUNT
FROM ANIMAL_OUTS
WHERE @hour < 23;
-- 가격대 별 상품 개수 구하기
SELECT TRUNCATE(PRICE, -4) as PRICE_GROUP, COUNT(*) as PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP;
-- 즐겨찾기가 가장 많은 식당 정보 출력하기
SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
FROM REST_INFO r, (SELECT FOOD_TYPE, MAX(FAVORITES) as MAX_F 
                   FROM REST_INFO 
                   GROUP BY FOOD_TYPE) ar
WHERE r.FOOD_TYPE=ar.FOOD_TYPE AND r.FAVORITES=ar.MAX_F
ORDER BY r.FOOD_TYPE DESC;
-- 식품분류별 가장 비싼 식품의 정보 구하기
SELECT f.CATEGORY AS CATEGORY, f.PRICE AS MAX_PRICE, f.PRODUCT_NAME AS PRODUCT_NAME
FROM FOOD_PRODUCT f, (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE 
                      FROM FOOD_PRODUCT
                      GROUP BY CATEGORY) t
WHERE f.CATEGORY = t.CATEGORY AND f.PRICE=t.MAX_PRICE AND f.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;
-- 년, 월, 성별 별 상품 구매 회원 수 구하기
SELECT YEAR(o.SALES_DATE) AS YEAR, MONTH(o.SALES_DATE) AS MONTH, u.GENDER AS GENDER, COUNT(DISTINCT u.USER_ID) AS USERS
FROM USER_INFO u, ONLINE_SALE o
WHERE u.USER_ID=o.USER_ID AND u.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;

