-- 없어진 기록 찾기
SELECT outs.ANIMAL_ID, outs.NAME
FROM ANIMAL_INS AS ins RIGHT JOIN ANIMAL_OUTS AS outs ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE ins.ANIMAL_ID IS NULL;
-- 있었는데요 없었습니다
SELECT outs.ANIMAL_ID, outs.NAME
FROM ANIMAL_INS AS ins JOIN ANIMAL_OUTS AS outs ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE ins.DATETIME > outs.DATETIME
ORDER BY ins.DATETIME;
-- 오랜 기간 보호한 동물
SELECT ins.NAME, ins.DATETIME
FROM ANIMAL_INS AS ins LEFT JOIN ANIMAL_OUTS AS outs ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE outs.ANIMAL_ID IS NULL
ORDER BY ins.DATETIME
LIMIT 3;
-- 보호소에서 중성화한 동물
SELECT outs.ANIMAL_ID, outs.ANIMAL_TYPE, outs.NAME
FROM ANIMAL_INS AS ins JOIN ANIMAL_OUTS AS outs ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE ins.SEX_UPON_INTAKE LIKE "Intact%" AND outs.SEX_UPON_OUTCOME NOT LIKE "INTACT%"
ORDER BY ins.ANIMAL_ID;

