-- 루시와 엘라 찾기
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN ('Lucy', 'Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty')
ORDER BY ANIMAL_ID;
-- 이름에 el이 들어가는 동물 찾기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE ANIMAL_TYPE = "Dog" AND NAME REGEXP("[eE][lL]")
ORDER BY NAME;
-- 중성화 여부 파악하기
SELECT ANIMAL_ID, NAME, IF(SEX_UPON_INTAKE REGEXP('Neutered|Spayed'), 'O' , 'X') 
FROM ANIMAL_INS;
-- 오랜 기간 보호한 동물(2)
SELECT outs.ANIMAL_ID, outs.NAME
FROM ANIMAL_INS AS ins JOIN ANIMAL_OUTS AS outs ON ins.ANIMAL_ID = outs.ANIMAL_ID
ORDER BY outs.DATETIME - ins.DATETIME DESC
LIMIT 2;
-- DATETIME에서 DATE로 형 변환
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d')
FROM ANIMAL_INS
ORDER BY ANIMAL_ID ASC;
-- 카테고리 별 상품 개수 구하기
SELECT LEFT(PRODUCT_CODE, 2) as CATEGORY, COUNT(*) as PRODUCTS
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY;
-- 조건별로 분류하여 주문상태 출력하기
SELECT ORDER_ID, PRODUCT_ID, date_format(OUT_DATE, '%Y-%m-%d') AS OUT_DATE, IF(ISNULL(OUT_DATE), '출고미정', IF(OUT_DATE<='2022-05-01', '출고완료', '출고대기')) AS '출고여부'
FROM FOOD_ORDER
ORDER BY ORDER_ID;
